----TABLE:CB_CIF_CLIENT---------
DROP TABLE IF EXISTS OMI.CB_CIF_CLIENT;
CREATE TABLE OMI.CB_CIF_CLIENT( 
CLIENT_KEY DECIMAL(15) not null comment '内部Key',
CLIENT_NO STRING comment '客户号',
CLIENT_TYPE STRING comment '客户类型',
CATEGORY_TYPE STRING comment '客户细分类型',
CLIENT_GRP STRING comment '客户组',
CLIENT_SHORT STRING not null comment '客户简称',
CH_CLIENT_NAME STRING comment '客户名称（中）',
CLIENT_NAME STRING comment '客户名称（英）',
NAME_SUFFIX STRING comment '客户名后缀',
CLIENT_MNEMONIC STRING comment '助记名称',
CLIENT_ALIAS STRING comment '别名',
ADDRESS STRING comment '地址',
ACCT_EXEC STRING comment '客户经理',
COUNTRY_LOC STRING comment '国籍',
STATE_LOC STRING comment '省州',
CLIENT_CITY STRING comment '城市代码',
COUNTRY_CITIZEN STRING comment '居住国家',
COUNTRY_RISK STRING comment '风险控制国家',
CTRL_BRANCH STRING comment '控制分行',
PROFIT_CENTRE STRING comment '利润中心',
CLASS_1 STRING comment '分类1',
CLASS_2 STRING comment '分类2',
CLASS_3 STRING comment '分类3',
CLASS_4 STRING comment '分类4',
CLASS_5 STRING comment '分类5',
NARRATIVE STRING comment '摘要',
INTERNAL_IND STRING comment '是否为内部客户',
TAXABLE_IND STRING comment '是否收税',
CLIENT_SPREAD DECIMAL(15,8) comment '客户汇率优惠比例',
RISK_WEIGHT DECIMAL(5,2) comment '风险权重',
STATUS_INFO STRING comment '状态描述',
CLIENT_STATUS STRING comment '客户状态',
TRAN_STATUS STRING comment '客户交易状态',
CLOSED_DATE STRING comment '关闭日期',
CLIENT_INDICATOR STRING not null comment '客户标识',
DISTRICT STRING comment '地区',
POSTAL_CODE STRING comment '邮政代码',
CONTROL_DEPT STRING comment '部门',
SOURCE_TYPE STRING comment '渠道',
WRITTEN_LANGUAGE STRING comment '书写语言',
SPOKEN_LANGUAGE STRING comment '交流语言',
PRINT_LANGUAGE STRING comment '打印语言',
INLAND_OFFSHORE STRING comment '境内境外',
TEMP_CLIENT STRING comment '是否为临时客户',
PEP_IND STRING comment '资料不全标识',
INFO_LACK STRING comment 'PEP标识',
CLASS_LEVEL STRING comment '综合评级',
CLASS_LEVEL_DATE STRING comment '评级日期',
OLD_CLIENT_NO STRING comment '原系统客户号',
CREATION_USER_ID STRING comment '创建用户',
CREATION_DATE STRING comment '创建日期',
LAST_CHANGE_USER_ID STRING comment '更新用户',
LAST_CHANGE_DATE STRING comment '更新日期',
BLACKLIST_IND STRING comment '是否黑名单客户',
COMPANY STRING comment '法人代码',
INDUSTRY STRING comment '通用行业代码',
BUSINESS STRING comment '行业代码',
CR_RATING STRING comment '客户等级',
VOUCHER_TYPE STRING comment '开票类型',
TAXPAYER_TYPE STRING comment '纳税人类型',
IS_FORMAL STRING comment '是否弱实名客户',
TRAN_TIMESTAMP STRING comment '交易时间戳',
TRAN_TIME DECIMAL(11) comment '交易时间',
ROUTER_KEY STRING comment '分库路由关键字') 
COMMENT '客户信息表' 
CLUSTERED BY (CLIENT_KEY) INTO 11 BUCKETS 
stored as orc 
TBLPROPERTIES ('transactional'='true');

