!set plsqlUseSlash true
--专题模块数据-date.xlsx
CREATE EXTERNAL TABLE IF NOT EXISTS TBO.ZS_ZTMKSJ_QYZPJBXX
(QYMC STRING COMMENT '企业名称'
,TYSHXYDM STRING COMMENT '统一社会信用代码'
,ZPQYMC STRING COMMENT '招聘企业名称'
,ZPLY STRING COMMENT '招聘来源'
,ZPLYBM STRING COMMENT '招聘来源编码'
,GSGM STRING COMMENT '公司规模'
,GSXY STRING COMMENT '公司行业'
,GSDZ STRING COMMENT '公司地址'
,GSZY STRING COMMENT '公司主页'
,GSJS STRING COMMENT '公司介绍'
,ZPZLNR STRING COMMENT '招聘专栏内容'
,FBRQ STRING COMMENT '发布日期'
)
COMMENT '企业招聘基本信息'
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES('input.delimited' = '|+|')
STORED AS TEXTFILE
LOCATION '/dw/tbo/zs/zs_ztmksj_qyzpjbxx';

CREATE EXTERNAL TABLE IF NOT EXISTS TBO.ZS_ZTMKSJ_SSWF
(QYMC STRING COMMENT '企业名称'
,TYSHXYDM STRING COMMENT '统一社会信用代码'
,NSRDJMC STRING COMMENT '纳税人登记名称'
,NSRSBH STRING COMMENT '纳税人识别号'
,FRGYXX STRING COMMENT '法人概要信息'
,FYZJZRDCWFZRGYXX STRING COMMENT '负有直接责任的财务负责人概要信息'
,FYZJZRDZJJGGYXX STRING COMMENT '负有直接责任的中介机构概要信息'
,AJXZ STRING COMMENT '案件性质'
,XGFLYJJSWCLCFQK STRING COMMENT '相关法律依据及税务处理处罚情况'
)
COMMENT '税收违法'
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES('input.delimited' = '|+|')
STORED AS TEXTFILE
LOCATION '/dw/tbo/zs/zs_ztmksj_sswf';

CREATE EXTERNAL TABLE IF NOT EXISTS TBO.ZS_ZTMKSJ_TRZXX
(QYMC STRING COMMENT '企业名称'
,TYSHXYDM STRING COMMENT '统一社会信用代码'
,PLRQ STRING COMMENT '披露日期'
,SJQC STRING COMMENT '事件全称'
,TZFMC STRING COMMENT '投资方名称'
,RZFMCJC STRING COMMENT '融资方名称简称'
,TZXZ_LC STRING COMMENT '投资性质/轮次'
,TZSJ STRING COMMENT '投资时间'
,TZGQBL STRING COMMENT '投资股权比例'
,TZJE STRING COMMENT '投资金额'
,BZ STRING COMMENT '币种'
,GICSDM STRING COMMENT 'GICS代码'
,GICSMC STRING COMMENT 'GICS名称'
,DQMC STRING COMMENT '地区名称'
,QYJD STRING COMMENT '企业阶段'
,SFSS STRING COMMENT '是否上市'
)
COMMENT '投融资信息'
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES('input.delimited' = '|+|')
STORED AS TEXTFILE
LOCATION '/dw/tbo/zs/zs_ztmksj_trzxx';

CREATE EXTERNAL TABLE IF NOT EXISTS TBO.ZS_ZTMKSJ_ZLFLXX
(QYMC STRING COMMENT '企业名称'
,TYSHXYDM STRING COMMENT '统一社会信用代码'
,SQGGH STRING COMMENT '授权公告号'
,SQH STRING COMMENT '申请号'
,BZR STRING COMMENT '颁证日'
,FLZTGGR STRING COMMENT '法律状态公告日'
,FLZT STRING COMMENT '法律状态'
,FLZTXX STRING COMMENT '法律状态信息'
)
COMMENT '专利法律信息'
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES('input.delimited' = '|+|')
STORED AS TEXTFILE
LOCATION '/dw/tbo/zs/zs_ztmksj_zlflxx';

CREATE EXTERNAL TABLE IF NOT EXISTS TBO.ZS_ZTMKSJ_ZLJBXX
(QYMC STRING COMMENT '企业名称'
,TYSHXYDM STRING COMMENT '统一社会信用代码'
,TYSHXYDM2 STRING COMMENT '统一社会信用代码'
,GKH STRING COMMENT '公开(公告)号'
,GKR STRING COMMENT '公开(公告)日'
,SQH STRING COMMENT '申请号'
,ZLLXBM STRING COMMENT '专利类型编码'
,ZLLX STRING COMMENT '专利类型'
,SQR STRING COMMENT '申请日'
,ZLH STRING COMMENT '专利号'
,ZLMC STRING COMMENT '专利名称'
,ZFLH STRING COMMENT '主分类号'
,FLH STRING COMMENT '分类号'
,ZLR STRING COMMENT '申请(专利权)人'
,FMR STRING COMMENT '发明(设计)人'
,DZ STRING COMMENT '地址'
,ZLDLJG STRING COMMENT '专利代理机构'
,ZLDLJGWYBSM STRING COMMENT '专利代理机构唯一标识码'
,DLR STRING COMMENT '代理人'
,SCY STRING COMMENT '审查员'
)
COMMENT '专利基本信息'
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES('input.delimited' = '|+|')
STORED AS TEXTFILE
LOCATION '/dw/tbo/zs/zs_ztmksj_zljbxx';

CREATE EXTERNAL TABLE IF NOT EXISTS TBO.ZS_ZTMKSJ_ZPZZQ
(QYMC STRING COMMENT '企业名称'
,TYSHXYDM STRING COMMENT '统一社会信用代码'
,ZPMC STRING COMMENT '作品名称'
,ZPLBWDM STRING COMMENT '作品类别维度码'
,ZZQRXM STRING COMMENT '著作权人姓名/名称'
,GJ STRING COMMENT '国籍'
,SF STRING COMMENT '省份'
,CS STRING COMMENT '城市'
,ZZXM STRING COMMENT '作者姓名/名称'
,CZWCRQ STRING COMMENT '创作完成日期'
,SCFBRQ STRING COMMENT '首次发表日期'
,DJH STRING COMMENT '登记号'
,DJRQ STRING COMMENT '登记日期'
,FBRQ STRING COMMENT '发布日期'
,YWZJ STRING COMMENT '业务主键'
,ZPLB STRING COMMENT '作品类别'
)
COMMENT '作品著作权'
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES('input.delimited' = '|+|')
STORED AS TEXTFILE
LOCATION '/dw/tbo/zs/zs_ztmksj_zpzzq';


CREATE EXTERNAL TABLE IF NOT EXISTS TBO.ZS_ZTMKSJ_FYGG
(QYMC STRING COMMENT '企业名称'
,TYSHXYDM STRING COMMENT '统一社会信用代码'
,GGFL STRING COMMENT '公告分类'
,GGR STRING COMMENT '公告人'
,DSR STRING COMMENT '当事人'
,GGSJ STRING COMMENT '公告时间'
,ZXWSNR STRING COMMENT '执行文书内容'
,GGRDQBM STRING COMMENT '公告人地区编码'
,GGRDQMC STRING COMMENT '公告人地区名称'
)
COMMENT '法院公告'
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES('input.delimited' = '|+|')
STORED AS TEXTFILE
LOCATION '/dw/tbo/zs/zs_ztmksj_fygg';

--企业招聘职位信息
CREATE EXTERNAL TABLE IF NOT EXISTS TBO.ZS_QYZPZWXX
(QYMC STRING COMMENT '企业名称'
  , TYSHXYDM STRING COMMENT '统一社会信用代码'
  , QYMC2 STRING COMMENT '企业名称'
  , ZPLY STRING COMMENT '招聘来源'
  , ZPLYBM STRING COMMENT '招聘来源编码'
  , ZWMC STRING COMMENT '职位名称'
  , GZJY STRING COMMENT '工作经验'
  , XLYQ STRING COMMENT '学历要求'
  , GLJY STRING COMMENT '管理经验'
  , ZPBM STRING COMMENT '招聘部门'
  , XSRS STRING COMMENT '下属人数'
  , ZPRS STRING COMMENT '招聘人数'
  , XZFW STRING COMMENT '薪资范围'
  , NLFW STRING COMMENT '年龄范围'
  , ZWLB STRING COMMENT '职位类别'
  , GZDD STRING COMMENT '工作地点'
  , ZWMS CLOB COMMENT '职位描述'
  , GZZT STRING COMMENT '工作状态'
  , HBDX STRING COMMENT '汇报对象'
  , XBYQ STRING COMMENT '性别要求'
  , YYYQ STRING COMMENT '语言要求'
  , ZYYQ STRING COMMENT '专业要求'
  , FLDY STRING COMMENT '福利待遇'
  , SBDZ STRING COMMENT '上班地址'
  , ZWFBSJ STRING COMMENT '职位发布时间'
  , ZWGXSJ STRING COMMENT '职位更新时间')
COMMENT '企业招聘职位信息'
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES('input.delimited' = '\001')
STORED AS TEXTFILE
LOCATION '/dw/tbo/zs/zs_qyzpzwxx';

--企业控制路径_对外投资
CREATE EXTERNAL TABLE IF NOT EXISTS TBO.ZS_QYKZLJ_DWTZ
(TARGET_QY STRING COMMENT '目标企业'
,DWTZ STRING COMMENT '对外投资'
,CZBL_SFKG STRING COMMENT '出资比例/(是否控股)'
,ZZKGGD STRING COMMENT '最终控股股东'
,SJJD STRING COMMENT '上级节点'
,JDLX STRING COMMENT '节点类型'
,TYSHXYDM_GRBSM STRING COMMENT '统一社会信用代码/个人标识码'
,ZCZB STRING COMMENT '注册资本'
,XYML STRING COMMENT '行业门类'
,CLRQ STRING COMMENT '成立日期'
)
COMMENT '企业控制路径_对外投资'
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES('input.delimited' = '|+|')
STORED AS TEXTFILE
LOCATION '/dw/tbo/zs/zs_qykzlj_dwtz';

--企业控制路径_股东
CREATE EXTERNAL TABLE IF NOT EXISTS TBO.ZS_QYKZLJ_GD
(TARGET_QY STRING COMMENT '目标企业'
,GD STRING COMMENT '股东'
,CZBL_SFKG STRING COMMENT '出资比例/(是否控股)'
,ZZKGGD STRING COMMENT '最终控股股东'
,SJJD STRING COMMENT '上级节点'
,JDLX STRING COMMENT '节点类型'
,TYSHXYDM_GRBSM STRING COMMENT '统一社会信用代码/个人标识码'
,ZCZB STRING COMMENT '注册资本'
,XYML STRING COMMENT '行业门类'
,CLRQ STRING COMMENT '成立日期'
)
COMMENT '企业控制路径_股东'
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES('input.delimited' = '|+|')
STORED AS TEXTFILE
LOCATION '/dw/tbo/zs/zs_qykzlj_gd';

--企业控制路径_实际控制人
CREATE EXTERNAL TABLE IF NOT EXISTS TBO.ZS_QYKZLJ_SJKZR
(TARGET_QY STRING COMMENT '目标企业'
,SJKZR STRING COMMENT '实际控制人'
,CZBL_SFKG STRING COMMENT '出资比例/(是否控股)'
,ZZKGGD STRING COMMENT '最终控股股东'
,SJJD STRING COMMENT '上级节点'
,JDLX STRING COMMENT '节点类型'
,TYSHXYDM_GRBSM STRING COMMENT '统一社会信用代码/个人标识码'
,ZCZB STRING COMMENT '注册资本'
,XYML STRING COMMENT '行业门类'
,CLRQ STRING COMMENT '成立日期'
)
COMMENT '企业控制路径_实际控制人'
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES('input.delimited' = '|+|')
STORED AS TEXTFILE
LOCATION '/dw/tbo/zs/zs_qykzlj_sjkzr';

--企业查询数据-date.xlsx
CREATE EXTERNAL TABLE IF NOT EXISTS TBO.ZS_QYCXSJ_DCDY_BGXX
(QYENTID STRING COMMENT '企业ENTID'
,BGRQ STRING COMMENT '变更日期'
,BGNR STRING COMMENT '变更内容'
,DJBH STRING COMMENT '登记编号'
)
COMMENT '动产抵押_变更信息'
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES('input.delimited' = '|+|')
STORED AS TEXTFILE
LOCATION '/dw/tbo/zs/zs_qycxsj_dcdy_bgxx';

CREATE EXTERNAL TABLE IF NOT EXISTS TBO.ZS_QYCXSJ_BGXX
(QYENTID STRING COMMENT '企业ENTID'
,BGHNR STRING COMMENT '变更后内容'
,BGQNR STRING COMMENT '变更前内容'
,GQBGRQ STRING COMMENT '股权变更日期'
,BGSX STRING COMMENT '变更事项'
)
COMMENT '变更信息'
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES('input.delimited' = '|+|')
STORED AS TEXTFILE
LOCATION '/dw/tbo/zs/zs_qycxsj_bgxx';

CREATE EXTERNAL TABLE IF NOT EXISTS TBO.ZS_QYCXSJ_YZWF
(QYENTID STRING COMMENT '企业ENTID'
,LRSJ STRING COMMENT '列入时间'
,LRYY STRING COMMENT '列入原因'
,LRZCJDJG STRING COMMENT '列入作出决定机关'
,LRZCJDWH STRING COMMENT '列入作出决定文号'
,YCSJ STRING COMMENT '移出时间'
,YCYY STRING COMMENT '移出原因'
,YCZCJDJG STRING COMMENT '移出作出决定机关'
,YCZCJDWH STRING COMMENT '移出作出决定文号'
)
COMMENT '严重违法'
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES('input.delimited' = '|+|')
STORED AS TEXTFILE
LOCATION '/dw/tbo/zs/zs_qycxsj_yzwf';

CREATE EXTERNAL TABLE IF NOT EXISTS TBO.ZS_QYCXSJ_XZCFJBXX
(QYENTID STRING COMMENT '企业ENTID'
,ZYWFSS STRING COMMENT '主要违法事实'
,CFJG STRING COMMENT '处罚机关'
,CFJGMC STRING COMMENT '处罚机关名称'
,XZCFNR STRING COMMENT '行政处罚内容'
,CFJDSQFRQ STRING COMMENT '处罚决定书签发日期'
,CFJDWS STRING COMMENT '处罚决定文书'
,GSRQ STRING COMMENT '公示日期'
)
COMMENT '行政处罚基本信息'
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES('input.delimited' = '|+|')
STORED AS TEXTFILE
LOCATION '/dw/tbo/zs/zs_qycxsj_xzcfjbxx';

CREATE EXTERNAL TABLE IF NOT EXISTS TBO.ZS_QYCXSJ_NB_QYDWTZXX
(QYENTID STRING COMMENT '企业ENTID'
,NBID STRING COMMENT '年报ID'
,TYSHXYDM STRING COMMENT '统一社会信用代码'
,QYMC STRING COMMENT '企业名称'
,ZCH STRING COMMENT '注册号'
)
COMMENT '年报_企业对外投资信息'
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES('input.delimited' = '|+|')
STORED AS TEXTFILE
LOCATION '/dw/tbo/zs/zs_qycxsj_nb_qydwtzxx';

CREATE EXTERNAL TABLE IF NOT EXISTS TBO.ZS_QYCXSJ_QYDWTZXX
(QYENTID STRING COMMENT '企业ENTID'
,QYZSL STRING COMMENT '企业总数量'
,ZXRQ STRING COMMENT '注销日期'
,CZFS STRING COMMENT '出资方式'
,RJCZBZ STRING COMMENT '认缴出资币种'
,TYSHXYDM STRING COMMENT '统一社会信用代码'
,QYJGMC STRING COMMENT '企业机构名称'
,QYZT STRING COMMENT '企业状态'
,QYJGLX STRING COMMENT '企业(机构)类型'
,KYRQ STRING COMMENT '开业日期'
,CZBL STRING COMMENT '出资比例'
,DSRXM STRING COMMENT '当事人姓名'
,ZCZB STRING COMMENT '注册资本(万元)'
,ZCZBBZ STRING COMMENT '注册资本币种'
,ZCH STRING COMMENT '注册号'
,DJJG STRING COMMENT '登记机关'
,ZCDZXZQBH STRING COMMENT '注册地址行政区编号'
,DXRQ STRING COMMENT '吊销日期'
,RJCZE STRING COMMENT '认缴出资额(万元)'
)
COMMENT '企业对外投资信息'
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES('input.delimited' = '|+|')
STORED AS TEXTFILE
LOCATION '/dw/tbo/zs/zs_qycxsj_qydwtzxx';

CREATE EXTERNAL TABLE IF NOT EXISTS TBO.ZS_QYCXSJ_QYYCML
(QYENTID STRING COMMENT '企业ENTID'
,QYMC STRING COMMENT '企业名称'
,QYJGLX STRING COMMENT '企业(机构)类型'
,LRSJ STRING COMMENT '列入时间'
,LRYY STRING COMMENT '列入原因'
,YCSJ STRING COMMENT '移出时间'
,YCYY STRING COMMENT '移出原因'
,ZCH STRING COMMENT '注册号'
,TYSHXYDM STRING COMMENT '统一社会信用代码'
,YCJGMC STRING COMMENT '移除机关名称'
,LRJGMC STRING COMMENT '列入机关名称'
)
COMMENT '企业异常名录'
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES('input.delimited' = '|+|')
STORED AS TEXTFILE
LOCATION '/dw/tbo/zs/zs_qycxsj_qyycml';

CREATE EXTERNAL TABLE IF NOT EXISTS TBO.ZS_QYCXSJ_FZJG
(QYENTID STRING COMMENT '企业ENTID'
,FZJGMC STRING COMMENT '分支机构名称'
,FZJGTYSHXYDM STRING COMMENT '分支机构统一社会信用代码'
,FZJGDJJG STRING COMMENT '分支机构登记机关'
,FZJGQYZCH STRING COMMENT '分支机构企业注册号'
)
COMMENT '分支机构'
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES('input.delimited' = '|+|')
STORED AS TEXTFILE
LOCATION '/dw/tbo/zs/zs_qycxsj_fzjg';

CREATE EXTERNAL TABLE IF NOT EXISTS TBO.ZS_QYCXSJ_QYFDDBRDWTZXX
(QYENTID STRING COMMENT '企业ENTID'
,ZXRQ STRING COMMENT '注销日期'
,CZFS STRING COMMENT '出资方式'
,TYSHXYDM STRING COMMENT '统一社会信用代码'
,RJCZBZ STRING COMMENT '认缴出资币种'
,QYMC STRING COMMENT '企业名称'
,QYZT STRING COMMENT '企业状态'
,QYJGLX STRING COMMENT '企业(机构)类型'
,KYRQ STRING COMMENT '开业日期'
,CZBL STRING COMMENT '出资比例'
,DSRXM STRING COMMENT '当事人姓名'
,QYZSL STRING COMMENT '企业总数量'
,ZCZB STRING COMMENT '注册资本(万元)'
,ZCZBBZ STRING COMMENT '注册资本币种'
,ZCH STRING COMMENT '注册号'
,DJJG STRING COMMENT '登记机关'
,ZCDZXZQBH STRING COMMENT '注册地址行政区编号'
,DXRQ STRING COMMENT '吊销日期'
,RJCZE STRING COMMENT '认缴出资额(万元)'
)
COMMENT '企业法定代表人对外投资信息'
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES('input.delimited' = '|+|')
STORED AS TEXTFILE
LOCATION '/dw/tbo/zs/zs_qycxsj_qyfddbrdwtzxx';

CREATE EXTERNAL TABLE IF NOT EXISTS TBO.ZS_QYCXSJ_FDDBRQTGSRZ
(QYENTID STRING COMMENT '企业ENTID'
,ZXRQ STRING COMMENT '注销日期'
,TYSHXYDM STRING COMMENT '统一社会信用代码'
,QYMC STRING COMMENT '企业名称'
,QYZT STRING COMMENT '企业状态'
,QYJGLX STRING COMMENT '企业(机构)类型'
,KYRQ STRING COMMENT '开业日期'
,SFFDDBR STRING COMMENT '是否法定代表人'
,DSRXM STRING COMMENT '当事人姓名'
,ZW STRING COMMENT '职务'
,QYZSL STRING COMMENT '企业总数量'
,ZCZB STRING COMMENT '注册资本(万元)'
,ZCZBBZ STRING COMMENT '注册资本币种'
,ZCH STRING COMMENT '注册号'
,DJJG STRING COMMENT '登记机关'
,ZCDZXZQBH STRING COMMENT '注册地址行政区编号'
,DXRQ STRING COMMENT '吊销日期'
)
COMMENT '法定代表人其他公司任职'
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES('input.delimited' = '|+|')
STORED AS TEXTFILE
LOCATION '/dw/tbo/zs/zs_qycxsj_fddbrqtgsrz';

CREATE EXTERNAL TABLE IF NOT EXISTS TBO.ZS_QYCXSJ_CCJC
(QYENTID STRING COMMENT '企业ENTID'
,CJRQ STRING COMMENT '抽检日期'
,GGMC STRING COMMENT '公告名称'
,GGRQ STRING COMMENT '公告日期'
,JCHSJGMC STRING COMMENT '检查核实机关名称'
,JCHSJGDM STRING COMMENT '检查核实机关代码'
,JCJG STRING COMMENT '检查结果'
,SJLX STRING COMMENT '数据类型'
)
COMMENT '抽查检查'
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES('input.delimited' = '|+|')
STORED AS TEXTFILE
LOCATION '/dw/tbo/zs/zs_qycxsj_ccjc';

CREATE EXTERNAL TABLE IF NOT EXISTS TBO.ZS_QYCXSJ_SFXZJBXX
(QYENTID STRING COMMENT '企业ENTID'
,ZXFY STRING COMMENT '执行法院'
,XZGSTZSWH STRING COMMENT '协助公示通知书文号'
,BZ STRING COMMENT '币种'
,BZXR STRING COMMENT '被执行人'
,GQBGID STRING COMMENT '股权变更ID'
,BZXRID STRING COMMENT '被执行人ID'
,GQSE STRING COMMENT '股权数额'
,ZT STRING COMMENT '状态'
)
COMMENT '司法协助基本信息'
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES('input.delimited' = '|+|')
STORED AS TEXTFILE
LOCATION '/dw/tbo/zs/zs_qycxsj_sfxzjbxx';

CREATE EXTERNAL TABLE IF NOT EXISTS TBO.ZS_QYCXSJ_SFXZXQ
(QYENTID STRING COMMENT '企业ENTID'
,XXDJQX STRING COMMENT '续行冻结期限'
,XXDJQX_START STRING COMMENT '续行冻结期限自'
,XXDJQX_END STRING COMMENT '续行冻结期限至'
,ZXFY STRING COMMENT '执行法院'
,BZ STRING COMMENT '币种'
,ZXSX STRING COMMENT '执行事项'
,SXRQ STRING COMMENT '失效日期'
,SXYY STRING COMMENT '失效原因'
,XZZXTZSWH STRING COMMENT '协助执行通知书文号'
,DJQX STRING COMMENT '冻结期限'
,JDRQ STRING COMMENT '解冻日期'
,GQDJZT STRING COMMENT '股权冻结状态'
,DJQSRQ STRING COMMENT '冻结起始日期'
,DJJZRQ STRING COMMENT '冻结截至日期'
,ZJLX STRING COMMENT '证件类型'
,BZXR STRING COMMENT '被执行人'
,BZXRLX STRING COMMENT '被执行人类型'
,ZXCDSWH STRING COMMENT '执行裁定书文号'
,ZZBH STRING COMMENT '证照编号'
,ZZLX STRING COMMENT '证照类型'
,BDJGQSZSCTYSHXYDM STRING COMMENT '被冻结股权所在市场统一社会信用代码'
,BDJGQSZSCZTMC STRING COMMENT '被冻结股权所在市场主体名称'
,BZXRID STRING COMMENT '被执行人ID'
,GSRQ STRING COMMENT '公示日期'
,BDJGQSZSCZTZCH STRING COMMENT '被冻结股权所在市场主体注册号'
,GQSE STRING COMMENT '股权数额'
,GQSEDW STRING COMMENT '股权数额单位'
)
COMMENT '司法协助详情'
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES('input.delimited' = '|+|')
STORED AS TEXTFILE
LOCATION '/dw/tbo/zs/zs_qycxsj_sfxzxq';

CREATE EXTERNAL TABLE IF NOT EXISTS TBO.ZS_QYCXSJ_QSXX
(QYENTID STRING COMMENT '企业ENTID'
,QSFZR STRING COMMENT '清算负责人'
,QSZCY STRING COMMENT '清算组成员'
)
COMMENT '清算信息'
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES('input.delimited' = '|+|')
STORED AS TEXTFILE
LOCATION '/dw/tbo/zs/zs_qycxsj_qsxx';

CREATE EXTERNAL TABLE IF NOT EXISTS TBO.ZS_QYCXSJ_SSGPJBXX
(QYENTID STRING COMMENT '企业ENTID'
,SSGSQYJC STRING COMMENT '上市公司企业简称'
,SSCJYS STRING COMMENT '上市场交易所'
,SSCJYSBM STRING COMMENT '上市场交易所编码'
,SSZT STRING COMMENT '上市状态'
,ZQLBDM STRING COMMENT '证券类别代码'
,GPDM STRING COMMENT '股票代码'
)
COMMENT '上市股票基本信息'
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES('input.delimited' = '|+|')
STORED AS TEXTFILE
LOCATION '/dw/tbo/zs/zs_qycxsj_ssgpjbxx';

CREATE EXTERNAL TABLE IF NOT EXISTS TBO.ZS_QYCXSJ_DCDY_JBXX
(QYENTID STRING COMMENT '企业ENTID'
,GSRQ STRING COMMENT '公示日期'
,BDBZQSE STRING COMMENT '被担保债权数额'
,DJBH STRING COMMENT '登记编号'
,DJRQ STRING COMMENT '登记日期'
,DJJG STRING COMMENT '登记机关'
,ZT STRING COMMENT '状态'
)
COMMENT '动产抵押_基本信息'
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES('input.delimited' = '|+|')
STORED AS TEXTFILE
LOCATION '/dw/tbo/zs/zs_qycxsj_dcdy_jbxx';

CREATE EXTERNAL TABLE IF NOT EXISTS TBO.ZS_QYCXSJ_DCDY_ZXXX
(QYENTID STRING COMMENT '企业ENTID'
,ZXRQ STRING COMMENT '注销日期'
,ZXYY STRING COMMENT '注销原因'
,DJBH STRING COMMENT '登记编号'
)
COMMENT '动产抵押_注销信息'
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES('input.delimited' = '|+|')
STORED AS TEXTFILE
LOCATION '/dw/tbo/zs/zs_qycxsj_dcdy_zxxx';

CREATE EXTERNAL TABLE IF NOT EXISTS TBO.ZS_QYCXSJ_DCDY_BDBZZQXX
(QYENTID STRING COMMENT '企业ENTID'
,LXZWJSRQ STRING COMMENT '履行债务结束日期'
,LXZWKSRQ STRING COMMENT '履行债务开始日期'
,SE STRING COMMENT '数额'
,DBFW STRING COMMENT '担保范围'
,BZ STRING COMMENT '备注'
,ZL STRING COMMENT '种类'
,DJBH STRING COMMENT '登记编号'
)
COMMENT '动产抵押_被担保主债权信息'
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES('input.delimited' = '|+|')
STORED AS TEXTFILE
LOCATION '/dw/tbo/zs/zs_qycxsj_dcdy_bdbzzqxx';

CREATE EXTERNAL TABLE IF NOT EXISTS TBO.ZS_QYCXSJ_DCDY_DYWXX
(QYENTID STRING COMMENT '企业ENTID'
,QK STRING COMMENT '数量、质量、状况、所在地等情况'
,MC STRING COMMENT '名称'
,SYQHSYQGS STRING COMMENT '所有权或使用权归属'
,BZ STRING COMMENT '备注'
,DJBH STRING COMMENT '登记编号'
)
COMMENT '动产抵押_抵押物信息'
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES('input.delimited' = '|+|')
STORED AS TEXTFILE
LOCATION '/dw/tbo/zs/zs_qycxsj_dcdy_dywxx';

CREATE EXTERNAL TABLE IF NOT EXISTS TBO.ZS_QYCXSJ_DCDY_DYQRXX
(QYENTID STRING COMMENT '企业ENTID'
,DYQR_ZJHM STRING COMMENT '抵押权人证照/证件号码'
,DYQR_ZJLX STRING COMMENT '抵押权人证照/证件类型'
,SZD STRING COMMENT '所在地'
,DYQRMC STRING COMMENT '抵押权人名称'
,DJBH STRING COMMENT '登记编号'
)
COMMENT '动产抵押_抵押权人信息'
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES('input.delimited' = '|+|')
STORED AS TEXTFILE
LOCATION '/dw/tbo/zs/zs_qycxsj_dcdy_dyqrxx';

CREATE EXTERNAL TABLE IF NOT EXISTS TBO.ZS_QYCXSJ_ZYGLRY
(QYENTID STRING COMMENT '企业ENTID'
,RYXM STRING COMMENT '人员姓名'
,RYZSL STRING COMMENT '人员总数量'
,ZW STRING COMMENT '职务'
,ZWDM STRING COMMENT '职位代码'
)
COMMENT '主要管理人员'
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES('input.delimited' = '|+|')
STORED AS TEXTFILE
LOCATION '/dw/tbo/zs/zs_qycxsj_zyglry';

CREATE EXTERNAL TABLE IF NOT EXISTS TBO.ZS_QYCXSJ_SXBZXRXX
(QYENTID STRING COMMENT '企业ENTID'
,NL STRING COMMENT '年龄'
,SF STRING COMMENT '省份'
,FDDBR_FZRXM STRING COMMENT '法定代表人/负责人姓名'
,SFZHM_GSZCH STRING COMMENT '身份证号码/工商注册号'
,AH STRING COMMENT '案号'
,AJZT STRING COMMENT '案件状态'
,ZXFY STRING COMMENT '执行法院'
,SXBZXRXWJTQX STRING COMMENT '失信被执行人行为具体情形'
,SXFLWSQDDYW STRING COMMENT '生效法律文书确定的义务'
,TCRQ STRING COMMENT '退出日期'
,ZXYJWH STRING COMMENT '执行依据文号'
,ZCZXYJDW STRING COMMENT '做出执行依据单位'
,BZXRXM STRING COMMENT '被执行人姓名/名称'
,BZXRLXQK STRING COMMENT '被执行人履行情况'
,YLX STRING COMMENT '已履行(元)'
,FBSJ STRING COMMENT '发布时间'
,LASJ STRING COMMENT '立案时间'
,XB STRING COMMENT '性别'
,LX STRING COMMENT '类型'
,WLX STRING COMMENT '未履行(元)'
,SFZYSFZD STRING COMMENT '身份证原始发证地'
)
COMMENT '失信被执行人信息'
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES('input.delimited' = '|+|')
STORED AS TEXTFILE
LOCATION '/dw/tbo/zs/zs_qycxsj_sxbzxrxx';

CREATE EXTERNAL TABLE IF NOT EXISTS TBO.ZS_QYCXSJ_BZXRXX
(QYENTID STRING COMMENT '企业ENTID'
,NL STRING COMMENT '年龄'
,SF STRING COMMENT '省份'
,SFZHM_QYZCH STRING COMMENT '身份证号码/企业注册号'
,AH STRING COMMENT '案号'
,AJZT STRING COMMENT '案件状态'
,ZXFY STRING COMMENT '执行法院'
,ZXBD STRING COMMENT '执行标的（元）'
,BZXRXM STRING COMMENT '被执行人姓名/名称'
,LASJ STRING COMMENT '立案时间'
,XB STRING COMMENT '性别'
,LX STRING COMMENT '类型'
,SFZYSFZD STRING COMMENT '身份证原始发证地'
)
COMMENT '被执行人信息'
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES('input.delimited' = '|+|')
STORED AS TEXTFILE
LOCATION '/dw/tbo/zs/zs_qycxsj_bzxrxx';

CREATE EXTERNAL TABLE IF NOT EXISTS TBO.ZS_QYCXSJ_JYZX_JBXX
(QYENTID STRING COMMENT '企业ENTID'
,JYZXJG STRING COMMENT '简易注销结果'
,HZRQ STRING COMMENT '核准日期'
,TYSHXYDM STRING COMMENT '统一社会信用代码'
,QYMC STRING COMMENT '企业名称'
,GGKSRQ STRING COMMENT '公告开始日期'
,GGJZRQ STRING COMMENT '公告截止日期'
,ZCH STRING COMMENT '注册号'
,DJJG STRING COMMENT '登记机关'
,ZCDZXZQBH STRING COMMENT '注册地址行政区编号'
)
COMMENT '简易注销_基本信息'
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES('input.delimited' = '|+|')
STORED AS TEXTFILE
LOCATION '/dw/tbo/zs/zs_qycxsj_jyzx_jbxx';

CREATE EXTERNAL TABLE IF NOT EXISTS TBO.ZS_QYCXSJ_GLSXBZXRXX
(QYENTID STRING COMMENT '企业ENTID'
,NL STRING COMMENT '年龄'
,SF STRING COMMENT '省份'
,FDDBR STRING COMMENT '法定代表人/负责人姓名'
,SFZHM STRING COMMENT '身份证号码/工商注册号'
,AH STRING COMMENT '案号'
,AJZT STRING COMMENT '案件状态'
,ZXFY STRING COMMENT '执行法院'
,SXBZXRXWJTQX STRING COMMENT '失信被执行人行为具体情形'
,SXFLWSQDDYW STRING COMMENT '生效法律文书确定的义务'
,TCRQ STRING COMMENT '退出日期'
,ZXYJWH STRING COMMENT '执行依据文号'
,ZCZXYJDW STRING COMMENT '做出执行依据单位'
,BZXRXM STRING COMMENT '被执行人姓名/名称'
,BZXRLXQK STRING COMMENT '被执行人履行情况'
,YLX STRING COMMENT '已履行(元)'
,FBSJ STRING COMMENT '发布时间'
,LASJ STRING COMMENT '立案时间'
,XB STRING COMMENT '性别'
,LX STRING COMMENT '类型'
,WLX STRING COMMENT '未履行(元)'
,SFZYSFZD STRING COMMENT '身份证原始发证地'
)
COMMENT '关联失信被执行人信息'
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES('input.delimited' = '|+|')
STORED AS TEXTFILE
LOCATION '/dw/tbo/zs/zs_qycxsj_glsxbzxrxx';

CREATE EXTERNAL TABLE IF NOT EXISTS TBO.ZS_QYCXSJ_GLBZXRXX
(QYENTID STRING COMMENT '企业ENTID'
,NL STRING COMMENT '年龄'
,SF STRING COMMENT '省份'
,SFZHM_QYZCH STRING COMMENT '身份证号码/企业注册号'
,AH STRING COMMENT '案号'
,AJZT STRING COMMENT '案件状态'
,ZXFY STRING COMMENT '执行法院'
,ZXBD STRING COMMENT '执行标的（元）'
,BZXRXM STRING COMMENT '被执行人姓名/名称'
,LASJ STRING COMMENT '立案时间'
,XB STRING COMMENT '性别'
,LX STRING COMMENT '类型'
,SFZYSFZD STRING COMMENT '身份证原始发证地'
)
COMMENT '关联被执行人信息'
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES('input.delimited' = '|+|')
STORED AS TEXTFILE
LOCATION '/dw/tbo/zs/zs_qycxsj_glbzxrxx';

CREATE EXTERNAL TABLE IF NOT EXISTS TBO.ZS_QYCXSJ_GDJCZXX
(QYENTID STRING COMMENT '企业ENTID'
,SJCZE STRING COMMENT '实缴出资额'
,CZRQ STRING COMMENT '出资日期'
,CZFS STRING COMMENT '出资方式'
,CZFSDM STRING COMMENT '出资方式代码'
,TYSHXYDM STRING COMMENT '统一社会信用代码'
,RJCZBZDM STRING COMMENT '认缴出资币种代码'
,CZBL STRING COMMENT '出资比例'
,GDLX STRING COMMENT '股东类型'
,GDLXDM STRING COMMENT '股东类型代码'
,ZCZBBZ STRING COMMENT '注册资本币种'
,ZCH STRING COMMENT '注册号'
,GDMC STRING COMMENT '股东名称'
,RJCZE STRING COMMENT '认缴出资额(万元)'
)
COMMENT '股东及出资信息'
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES('input.delimited' = '|+|')
STORED AS TEXTFILE
LOCATION '/dw/tbo/zs/zs_qycxsj_gdjczxx';

CREATE EXTERNAL TABLE IF NOT EXISTS TBO.ZS_QYCXSJ_GQCZXX
(QYENTID STRING COMMENT '企业ENTID'
,CZGQSE STRING COMMENT '出质股权数额'
,CZRZJH STRING COMMENT '出质人证件/证件号'
,CZR STRING COMMENT '出质人'
,GSRQ STRING COMMENT '公示日期'
,ZQCZSLDJRQ STRING COMMENT '质权出质设立登记日期'
,DJBH STRING COMMENT '登记编号'
,ZT STRING COMMENT '状态'
,ZQRZJH STRING COMMENT '质权人证件/证件号'
,ZQRXM STRING COMMENT '质权人姓名'
,GLNR STRING COMMENT '关联内容'
)
COMMENT '股权出质信息'
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES('input.delimited' = '|+|')
STORED AS TEXTFILE
LOCATION '/dw/tbo/zs/zs_qycxsj_gqczxx';

CREATE EXTERNAL TABLE IF NOT EXISTS TBO.ZS_QYCXSJ_GQCZXX_ZXXX
(QYENTID STRING COMMENT '企业ENTID'
,GSRQ STRING COMMENT '公示日期'
,ZXYY STRING COMMENT '注销原因'
,GLNR STRING COMMENT '关联内容'
)
COMMENT '股权出质信息_注销信息'
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES('input.delimited' = '|+|')
STORED AS TEXTFILE
LOCATION '/dw/tbo/zs/zs_qycxsj_gqczxx_zxxx';

CREATE EXTERNAL TABLE IF NOT EXISTS TBO.ZS_QYCXSJ_NB_XGXX
(QYENTID STRING COMMENT '企业ENTID'
,XGSX STRING COMMENT '修改事项'
,BGHNR STRING COMMENT '变更后内容'
,BGQNR STRING COMMENT '变更前内容'
,GQBGRQ STRING COMMENT '股权变更日期'
,NBID STRING COMMENT '年报ID'
)
COMMENT '年报_修改信息'
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES('input.delimited' = '|+|')
STORED AS TEXTFILE
LOCATION '/dw/tbo/zs/zs_qycxsj_nb_xgxx';

CREATE EXTERNAL TABLE IF NOT EXISTS TBO.ZS_QYCXSJ_NB_GQBGXX
(QYENTID STRING COMMENT '企业ENTID'
,GQBGRQ STRING COMMENT '股权变更日期'
,NBID STRING COMMENT '年报ID'
,GDMC STRING COMMENT '股东名称'
,ZRHGQBL STRING COMMENT '转让后股权比例'
,ZRQGQBL STRING COMMENT '转让前股权比例'
)
COMMENT '年报_股权变更信息'
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES('input.delimited' = '|+|')
STORED AS TEXTFILE
LOCATION '/dw/tbo/zs/zs_qycxsj_nb_gqbgxx';

CREATE EXTERNAL TABLE IF NOT EXISTS TBO.ZS_QYCXSJ_NB_QYNBJBXX
(QYENTID STRING COMMENT '企业ENTID'
,SQDZ STRING COMMENT '申请地址'
,ZHNJRQ STRING COMMENT '最后年检日期'
,NBID STRING COMMENT '年报ID'
,ZHNJND STRING COMMENT '最后年检年度'
,JYZT STRING COMMENT '经营状态'
,TYSHXYDM STRING COMMENT '统一社会信用代码'
,YX STRING COMMENT '邮箱'
,QYMC STRING COMMENT '企业名称'
,QYKGQK STRING COMMENT '企业控股情况'
,QYZYYWHD STRING COMMENT '企业主营业务活动'
,YB STRING COMMENT '邮编'
,ZCH STRING COMMENT '注册号'
,LXRDH STRING COMMENT '联系人电话'
,NXCYRS STRING COMMENT '女性从业人数'
)
COMMENT '年报_企业年报基本信息'
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES('input.delimited' = '|+|')
STORED AS TEXTFILE
LOCATION '/dw/tbo/zs/zs_qycxsj_nb_qynbjbxx';

CREATE EXTERNAL TABLE IF NOT EXISTS TBO.ZS_QYCXSJ_NB_SHBXXX
(QYENTID STRING COMMENT '企业ENTID'
,NBID STRING COMMENT '年报ID'
,CZZGJBYLBXCBRS STRING COMMENT '城镇职工基本养老保险参保人数'
,SIYBXCBRS STRING COMMENT '失业保险参保人数'
,ZGJBYLBXCBRS STRING COMMENT '职工基本医疗保险参保人数'
,GSBXCBRS STRING COMMENT '工伤保险参保人数'
,SGYBXCBRS STRING COMMENT '生育保险参保人数'
,CJCZZGJBYLBXBQSJJFJE STRING COMMENT '参加城镇职工基本养老保险本期实际缴费金额'
,CJSIYBXBQSJJFJE STRING COMMENT '参加失业保险本期实际缴费金额'
,CJZGJBYLBXBQSJJFJE STRING COMMENT '参加职工基本医疗保险本期实际缴费金额'
,CJGSBXBQSJJFJE STRING COMMENT '参加工伤保险本期实际缴费金额'
,CJSGYBXBQSJJFJE STRING COMMENT '参加生育保险本期实际缴费金额'
,DWCJCZZGJBYLBXJFJS STRING COMMENT '单位参加城镇职工基本养老保险缴费基数'
,DWCJSIYBXJFJS STRING COMMENT '单位参加失业保险缴费基数'
,DWCJZGJBYLBXJFJS STRING COMMENT '单位参加职工基本医疗保险缴费基数'
,DWCJGSBXJFJS STRING COMMENT '单位参加工伤保险缴费基数'
,DWCJSGYBXJFJS STRING COMMENT '单位参加生育保险缴费基数'
,DWCJCZZGJBYLBXLJQJJE STRING COMMENT '单位参加城镇职工基本养老保险累计欠缴金额'
,DWCJSIYBXLJQJJE STRING COMMENT '单位参加失业保险累计欠缴金额'
,DWCJZGJBYLBXLJQJJE STRING COMMENT '单位参加职工基本医疗保险累计欠缴金额'
,CJGSBXLJQJJE STRING COMMENT '参加工伤保险累计欠缴金额'
,DWCJSGYBXLJQJJE STRING COMMENT '单位参加生育保险累计欠缴金额'
)
COMMENT '年报_社会保险信息'
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES('input.delimited' = '|+|')
STORED AS TEXTFILE
LOCATION '/dw/tbo/zs/zs_qycxsj_nb_shbxxx';

CREATE EXTERNAL TABLE IF NOT EXISTS TBO.ZS_QYCXSJ_NB_RJCZXX
( QYENTID STRING COMMENT '企业ENTID'
,NBID STRING COMMENT '年报ID'
,CZRQ STRING COMMENT '出资日期'
,CZFS STRING COMMENT '出资方式'
,GDMC STRING COMMENT '股东名称'
,LJRJE STRING COMMENT '累计认缴额'
)
COMMENT '年报_认缴出资信息'
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES('input.delimited' = '|+|')
STORED AS TEXTFILE
LOCATION '/dw/tbo/zs/zs_qycxsj_nb_rjczxx';

CREATE EXTERNAL TABLE IF NOT EXISTS TBO.ZS_QYCXSJ_NB_WZXX
(QYENTID STRING COMMENT '企业ENTID'
,NBID STRING COMMENT '年报ID'
,LJDZ STRING COMMENT '链接地址'
,WZHZWDMC STRING COMMENT '网站或者网店名称'
,WZWDLX STRING COMMENT '网站网店类型'
)
COMMENT '年报_网站信息'
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES('input.delimited' = '|+|')
STORED AS TEXTFILE
LOCATION '/dw/tbo/zs/zs_qycxsj_nb_wzxx';


CREATE EXTERNAL TABLE IF NOT EXISTS TBO.ZS_QYCXSJ_NB_QYSJCZXX
(QYENTID STRING COMMENT '企业ENTID'
,NBID STRING COMMENT '年报ID'
,CZRQ STRING COMMENT '出资日期'
,CZFS STRING COMMENT '出资方式'
,GDMC STRING COMMENT '股东名称'
,LJSJE STRING COMMENT '累计实缴额'
)
COMMENT '年报_企业实缴出资信息'
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES('input.delimited' = '|+|')
STORED AS TEXTFILE
LOCATION '/dw/tbo/zs/zs_qycxsj_nb_qysjczxx';

CREATE EXTERNAL TABLE IF NOT EXISTS TBO.ZS_QYCXSJ_QYJBXX
(QYENTID STRING COMMENT '企业ENTID'
,XKJYXM STRING COMMENT '许可经营项目'
,ZHNJND STRING COMMENT '最后年检年度'
,HZRQ STRING COMMENT '核准日期'
,ZXRQ STRING COMMENT '注销日期'
,TYSHXYDM STRING COMMENT '统一社会信用代码'
,ZS STRING COMMENT '住所'
,ZSSZXZQH STRING COMMENT '住所所在行政区划'
,YX STRING COMMENT '邮箱'
,QYENTID2 STRING COMMENT '企业ENTID'
,STLX STRING COMMENT '实体类型'
,QYMC STRING COMMENT '企业名称'
,CYM STRING COMMENT '曾用名'
,QYZT STRING COMMENT '企业状态'
,JYZTBM STRING COMMENT '经营状态编码'
,QYLX STRING COMMENT '企业(机构)类型'
,QYLXBM STRING COMMENT '企业(机构)类型编码'
,KYRQ STRING COMMENT '开业日期'
,FZR STRING COMMENT '法定代表人/负责人/执行事务合伙人'
,QYID STRING COMMENT '企业ID'
,GMJJXYDM STRING COMMENT '国民经济行业代码'
,GMJJXYMC STRING COMMENT '国民经济行业名称'
,QYLOGOTP STRING COMMENT '企业LOGO图片'
,JYQX_START STRING COMMENT '经营期限自'
,JYQX_END STRING COMMENT '经营期限至'
,ZZJGDM STRING COMMENT '组织机构代码'
,YB STRING COMMENT '邮编'
,QYEWM STRING COMMENT '企业二维码'
,SSZB STRING COMMENT '实收资本(万元)'
,ZCZB STRING COMMENT '注册资本(万元)'
,ZCZBBZ STRING COMMENT '注册资本币种'
,ZCZBBZDM STRING COMMENT '注册资本币种代码'
,SZCSBM STRING COMMENT '所在城市编码'
,ZCH STRING COMMENT '注册号'
,DJJG STRING COMMENT '登记机关'
,SZCS STRING COMMENT '所在城市'
,ZCDZXZQBH STRING COMMENT '注册地址行政区编号'
,SZQ STRING COMMENT '所在区/县'
,SZSF STRING COMMENT '所在省份'
,DXRQ STRING COMMENT '吊销日期'
,SJDBH STRING COMMENT '省节点编号'
,JYYWFW STRING COMMENT '经营业务范围'
)
COMMENT '企业基本信息'
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES('input.delimited' = '|+|')
STORED AS TEXTFILE
LOCATION '/dw/tbo/zs/zs_qycxsj_qyjbxx';


CREATE EXTERNAL TABLE IF NOT EXISTS TBO.ZS_QYCXSJ_DCDY_DJXX
(QYENTID STRING COMMENT '企业ENTID'
,BDBZQSE STRING COMMENT '被担保债权数额'
,DJBH STRING COMMENT '登记编号'
,DJRQ STRING COMMENT '登记日期'
,DJJG STRING COMMENT '登记机关'
,XZQHBM STRING COMMENT '行政区划编码'
,ZT STRING COMMENT '状态'
,HGZXBZBM STRING COMMENT '海关注销标志编码'
)
COMMENT '动产抵押_登记信息'
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES('input.delimited' = '|+|')
STORED AS TEXTFILE
LOCATION '/dw/tbo/zs/zs_qycxsj_dcdy_djxx';

--裁判文书
CREATE EXTERNAL TABLE IF NOT EXISTS TBO.ZS_CPWS
(QYMC STRING COMMENT '企业名称'
,TYSHXYDM STRING COMMENT '统一社会信用代码'
,BT STRING COMMENT '标题'
,AH STRING COMMENT '案号'
,DQ STRING COMMENT '地区'
,AJLX STRING COMMENT '案件类型'
,ZXFY STRING COMMENT '执行法院'
,SPRQ STRING COMMENT '审判日期'
,CXCPWSXQDIDH STRING COMMENT '查询裁判文书详情的id号'
,ZWNR CLOB COMMENT '正文内容'
)
COMMENT '裁判文书'
ROW FORMAT SERDE 'org.apache.hadoop.hive.contrib.serde2.MultiDelimitSerDe'
WITH SERDEPROPERTIES('input.delimited' = '\001')
STORED AS TEXTFILE
LOCATION '/dw/tbo/zs/zs_cpws';